// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeopleConnect.Infrastructure.Data;

#nullable disable

namespace PeopleConnect.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260427083419_seedPosttoDb")]
    partial class seedPosttoDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PeopleConnect.Domain.Entities.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Address = "Mirpur, Dhaka",
                            Contact = "01712345678",
                            Description = "I have arranged cooked meals for 50 families in need. Anyone facing food shortages can contact me for support.",
                            ImageUrl = "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c",
                            Name = "Ahnaf",
                            PostTitle = "Free Food Distribution for Poor Families",
                            PostType = "I Want to Give"
                        },
                        new
                        {
                            PostId = 2,
                            Address = "Farmgate, Dhaka",
                            Contact = "01732678932",
                            Description = "Looking for warm winter clothing for my family of 4. Jackets, sweaters, gloves - anything to help us through the cold season.",
                            ImageUrl = "https://unsplash.com/photos/man-holding-his-leather-jacket-P0W27GRvyww",
                            Name = "Abrar",
                            PostTitle = "Winter Clothes Needed for Family",
                            PostType = "I Need Help"
                        },
                        new
                        {
                            PostId = 3,
                            Address = "Thakugoan, Rangpur",
                            Contact = "01512345678",
                            Description = "I have school bags, notebooks, and stationery items for students from low-income families.",
                            ImageUrl = "https://images.unsplash.com/photo-1503676260728-1c00da094a0b",
                            Name = "Akash",
                            PostTitle = "School Bag and Stationery Donation",
                            PostType = "I Want to Give"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
